#!/bin/bash
#SBATCH -p RM
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=6
#SBATCH --mem-per-cpu=8G
#SBATCH --error=myjobresults-%J.err
#SBATCH --output=myjobresults-%J.out
#SBATCH --job-name=geo_scraper

python3 wellington_footprints.py $1 $2 $3