#!/bin/bash

#SBATCH -p RM
#SBATCH --nodes=1
#SBATCH --mem=48G
#SBATCH --ntasks-per-node=12
#SBATCH --mem-per-cpu=4G
#SBATCH --error=myjobresults-%J.err
#SBATCH --output=myjobresults-%J.out
#SBATCH --job-name=geo_scraper
#SBATCH -C EGRESS

python3 geo_scraper3_psc.py $1