#!/bin/bash

#SBATCH -p RM-shared
#SBATCH --nodes=1
#SBATCH --mem=48G
#SBATCH --ntasks-per-node=12
#SBATCH --mem-per-cpu=4G
#SBATCH --error=myjobresults-%J.err
#SBATCH --output=myjobresults-%J.out
#SBATCH --job-name=annotate
#SBATCH -C EGRESS

python3 annotate_peaks.py