#!/bin/bash

user=sgona

scancel -u $user
rm *.place
rm *.bam
rm *.fastq
rm *.fastq.gz
rm *.bed.gz
rm *inputdata.tsv

partition_count=40


for job in {1..20}
do
sbatch batch_submit_clean $user
sleep 1s
done
sbatch batch_submit_err

for job in {21..40}
do
sbatch batch_submit_clean_pool $user
sleep 1s
done