#!/bin/bash

partition_count=40
path=_inputdata.tsv

python3 partition_inputs.py $partition_count

for job in {1..20}
do
echo $job$path
sbatch batch_submit_scraper $job$path
sleep 1s
done
sbatch batch_submit_err

for job in {21..40}
do
echo $job$path
sbatch batch submit_scraper_pool $job$path
sleep 1s
done
